packages: []
catalogs:
  build:
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@nuxt/kit': ^3.17.5
    '@nuxtjs/color-mode': ^3.5.2
    '@nuxtjs/i18n': 10.0.0-beta.10
    '@pinia/nuxt': ^0.11.0
    '@unocss/eslint-config': ^66.1.3
    '@unocss/nuxt': ^66.1.3
    '@vite-pwa/nuxt': ^1.0.3
    '@vueuse/nuxt': ^13.3.0
    nuxt: ^3.17.5
    unocss: ^66.1.3
    unplugin: ^2.3.5
    vite: ^6.3.5
  dev:
    '@antfu/eslint-config': ^4.13.3
    '@types/codemirror': ^5.60.16
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-container': ^2.0.10
    '@types/turndown': ^5.0.5
    '@unocss/preset-wind3': ^66.2.1
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    lucide-vue-next: ^0.516.0
    reka-ui: ^2.3.1
    shadcn-nuxt: 2.2.0
    tailwind-merge: ^3.3.1
    typescript: ^5.8.3
    unocss-preset-animations: ^1.2.1
    unocss-preset-shadcn: ^0.5.0
    vue-tsc: ^2.2.10
  frontend:
    '@codemirror/commands': ^6.3.2
    '@codemirror/lang-markdown': ^6.3.2
    '@codemirror/state': ^6.5.2
    '@codemirror/view': ^6.37.1
    '@prisma/client': ^6.10.1
    '@vueuse/core': ^13.3.0
    codemirror: ^6.0.1
    font-awesome: ^4.7.0
    html-to-image: ^1.11.13
    jspdf: ^3.0.1
    jszip: ^3.10.1
    markdown-it: ^14.0.0
    markdown-it-container: ^4.0.0
    markdown-it-regex: ^0.2.2
    pinia: ^3.0.2
    prisma: ^6.10.1
    resume-theme: ^0.3.3
    turndown: ^7.2.0
    vue: ^3.5.16
    vue-color: ^3.1.0
    vue3-moveable: ^0.28.0
  icons:
    '@iconify-json/ri': ^1.2.5
    '@iconify/utils': ^2.3.0

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - core-js
  - prisma
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
