packages: []

catalogs:
  build:
    '@nuxt/devtools': ^2.6.2
    '@nuxt/eslint': ^1.5.2
    '@nuxt/kit': ^3.17.6
    '@nuxtjs/color-mode': ^3.5.2
    '@nuxtjs/i18n': 10.0.0-beta.10
    '@pinia/nuxt': ^0.11.1
    '@unocss/eslint-config': ^66.3.2
    '@unocss/nuxt': ^66.3.2
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.5.0
    bcrypt: ^6.0.0
    nodemailer: ^7.0.4
    nuxt: ^3.17.6
    unocss: ^66.3.2
    unplugin: ^2.3.5
    vite: ^6.3.5
  dev:
    '@antfu/eslint-config': ^4.16.2
    '@types/bcrypt': ^5.0.2
    '@types/codemirror': ^5.60.16
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-container': ^2.0.10
    '@types/nodemailer': ^6.4.17
    '@types/turndown': ^5.0.5
    '@unocss/preset-wind3': ^66.3.2
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    eslint: ^9.30.1
    eslint-plugin-format: ^1.0.1
    lucide-vue-next: ^0.516.0
    reka-ui: ^2.3.2
    shadcn-nuxt: 2.2.0
    tailwind-merge: ^3.3.1
    typescript: ^5.8.3
    unocss-preset-animations: ^1.2.1
    unocss-preset-shadcn: ^0.5.0
    vue-tsc: ^2.2.12
  frontend:
    '@auth/core': ^0.40.0
    '@auth/prisma-adapter': ^2.10.0
    '@codemirror/commands': ^6.8.1
    '@codemirror/lang-markdown': ^6.3.3
    '@codemirror/state': ^6.5.2
    '@codemirror/view': ^6.38.0
    '@prisma/client': ^6.11.1
    '@sidebase/nuxt-auth': ^1.0.0
    '@vueuse/core': ^13.5.0
    case-police: ^2.0.0
    codemirror: ^6.0.2
    font-awesome: ^4.7.0
    html-to-image: ^1.11.13
    jspdf: ^3.0.1
    jszip: ^3.10.1
    markdown-it: ^14.1.0
    markdown-it-container: ^4.0.0
    markdown-it-regex: ^0.2.2
    next-auth: 4.21.1
    pinia: ^3.0.3
    prisma: ^6.11.1
    resume-theme: ^0.3.3
    turndown: ^7.2.0
    vue: ^3.5.17
    vue-color: ^3.2.0
    vue3-moveable: ^0.28.0
  icons:
    '@iconify-json/ri': ^1.2.5
    '@iconify/utils': ^2.3.0

ignoredBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - core-js
  - prisma
  - vue-demi

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
