packages: []

catalogs:
  build:
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@nuxt/kit': ^3.17.5
    '@nuxtjs/color-mode': ^3.5.2
    '@nuxtjs/i18n': 10.0.0-beta.10
    '@pinia/nuxt': ^0.11.0
    '@unocss/eslint-config': ^66.1.3
    '@unocss/nuxt': ^66.1.3
    '@vite-pwa/nuxt': ^1.0.3
    '@vueuse/nuxt': ^13.3.0
    nuxt: ^3.17.5
    unocss: ^66.1.3
    unplugin: ^2.3.5
    vite: ^6.3.5

  dev:
    '@antfu/eslint-config': ^4.13.3
    '@types/codemirror': ^5.60.16
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-container': ^2.0.10
    eslint: ^9.28.0
    eslint-plugin-format: ^1.0.1
    typescript: ^5.8.3
    vue-tsc: ^2.2.10

  frontend:
    '@codemirror/commands': ^6.3.2
    '@codemirror/lang-markdown': ^6.3.2
    '@codemirror/state': ^6.5.2
    '@codemirror/view': ^6.37.1
    '@vueuse/core': ^13.3.0
    codemirror: ^6.0.1
    font-awesome: ^4.7.0
    html-to-image: ^1.11.13
    jspdf: ^3.0.1
    markdown-it: ^14.0.0
    markdown-it-container: ^4.0.0
    markdown-it-regex: ^0.2.2
    pinia: ^3.0.2
    resume-theme: ^0.1.5
    vue: ^3.5.16

  icons:
    '@iconify-json/ri': ^1.2.5
    '@iconify/utils': ^2.3.0

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
